name: Locust

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust
    - name: Run tests
      run: |
        locust -f locustfile.py --headless --run-time 1m --users 1 --spawn-rate 1 --host=http://localhost
        sleep 10s
