name: Test Job Communication

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    - name: Locust Load Test
      uses: apardo04/locust-github-action@1.1.0
      with:
        LOCUSTFILE: "locustfile.py"
        URL:  "http://localhost"
        USERS: "5"
        RATE: "5"
        RUNTIME: "10s"
          
