name: K6

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run local k6 test
          uses: grafana/k6-action@v0.3.1
          with:
            filename: k6.js
          env:
            BASE_URL: "http://127.0.0.1"        