name: K6

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run k6 local test

          uses: grafana/k6-action@v0.3.1
          with:
            cloud: false
            filename: k6.js
            flags: --vus 1 --duration 10s