name: Test Job Communication

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Locust Load Test
      uses: apardo04/locust-github-action@1.1.0
      with:
        LOCUSTFILE: "locustfile.py"
        URL:  "http://localhost"
        USERS: "5"
        RATE: "5"
        RUNTIME: "10s"
          
