name: Test Job Communication

on:
  workflow_dispatch:
  
jobs:
  run-httpbin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run httpbin Docker image
      run: |
        docker run -d --name httpbin kennethreitz/httpbin

  run-tests:
    needs: run-httpbin
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    - name: Run tests
      run: |
        locust -f locustfile.py --headless --run-time 1m --users 100 --spawn-rate 10

  kill-httpbin:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Kill httpbin Docker image
      run: |
        docker stop httpbin
